apiVersion: v1
kind: Service
metadata:
  name: boardgame-svc
  namespace: capstone
  labels:
    app: boardgame-app
spec:
  type: LoadBalancer
  selector:
    app: boardgame-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
